/**
 * Sync engine: reconciles the vault's Wedding Computer folder against
 * the server.
 *
 * The server is the source of truth. Etags drive change detection:
 * - server etag changed + local untouched          → overwrite local
 * - server etag changed + local edited             → conflict: local copy
 *   saved as <name>.conflict.md, server version wins
 * - server unchanged + local edited                → push (If-Match)
 * - on server but not local                        → download
 * - in our baseline but gone from server           → trash local copy
 * - local file we've never seen (no baseline)      → push as create;
 *   the server rejects files it can't ingest (e.g. a contact with no id)
 *
 * Conflict copies (*.conflict.md) and log.md are never pushed — log.md
 * is generated by the app, conflict copies are for the human to merge.
 */

import { App, Notice, TFile, TFolder, normalizePath } from 'obsidian'
import { WeddingComputerClient } from './api'

export type Baseline = Record<string, { etag: string; hash: string }>

export type SyncStats = {
  pulled: number
  pushed: number
  deleted: number
  conflicts: number
  errors: string[]
  vendor?: string
}

export class SyncEngine {
  /** Vault paths currently being written by the engine itself, so the
   * vault event handlers don't bounce our own writes back as pushes. */
  private applyingRemote = new Set<string>()

  constructor(
    private app: App,
    private client: WeddingComputerClient,
    private baseFolder: string,
    private baseline: Baseline,
    private persistBaseline: () => Promise<void>
  ) {}

  isApplyingRemote(vaultPath: string): boolean {
    return this.applyingRemote.has(vaultPath)
  }

  vaultPath(serverPath: string): string {
    return normalizePath(this.baseFolder ? `${this.baseFolder}/${serverPath}` : serverPath)
  }

  /** Map a vault path back to a server path, or null if outside the synced tree. */
  serverPath(vaultPath: string): string | null {
    const prefix = this.baseFolder ? normalizePath(this.baseFolder) + '/' : ''
    if (prefix && !vaultPath.startsWith(prefix)) return null
    const rel = vaultPath.slice(prefix.length)
    if (!rel.startsWith('contacts/') && !rel.startsWith('weddings/')) return null
    if (!rel.endsWith('.md')) return null
    return rel
  }

  private isPushable(serverPath: string): boolean {
    if (serverPath.endsWith('.conflict.md')) return false
    if (serverPath.endsWith('/log.md')) return false
    const filename = serverPath.split('/').pop() ?? ''
    if (filename.startsWith('.')) return false
    return true
  }

  /** Full reconcile: pull server changes, then push local ones. */
  async fullSync(): Promise<SyncStats> {
    const stats: SyncStats = { pulled: 0, pushed: 0, deleted: 0, conflicts: 0, errors: [] }

    const { vendor, files } = await this.client.listFiles()
    stats.vendor = vendor
    const serverByPath = new Map(files.map((f) => [f.path, f]))

    // ── Pull ──
    for (const remote of files) {
      try {
        await this.pullOne(remote.path, remote.etag, stats)
      } catch (err) {
        stats.errors.push(`${remote.path}: ${message(err)}`)
      }
    }

    // ── Server-side deletions ──
    for (const sp of Object.keys(this.baseline)) {
      if (serverByPath.has(sp)) continue
      try {
        await this.applyServerDeletion(sp, stats)
      } catch (err) {
        stats.errors.push(`${sp}: ${message(err)}`)
      }
    }

    // ── Push local changes and local-only files ──
    for (const file of this.collectSyncedFiles()) {
      const sp = this.serverPath(file.path)
      if (!sp || !this.isPushable(sp)) continue
      try {
        const content = await this.app.vault.read(file)
        const hash = await sha256(content)
        const base = this.baseline[sp]
        if (base && base.hash === hash) continue // unchanged since last sync
        await this.pushOne(sp, content, stats)
      } catch (err) {
        stats.errors.push(`${sp}: ${message(err)}`)
      }
    }

    await this.persistBaseline()
    return stats
  }

  /** Pull a single server file into the vault. */
  private async pullOne(sp: string, remoteEtag: string, stats: SyncStats): Promise<void> {
    const vp = this.vaultPath(sp)
    const existing = this.app.vault.getAbstractFileByPath(vp)
    const base = this.baseline[sp]

    if (existing instanceof TFile) {
      if (base && base.etag === remoteEtag) return // server unchanged; push phase handles local edits

      const localContent = await this.app.vault.read(existing)
      const localHash = await sha256(localContent)
      const { content, etag } = await this.client.getFile(sp)
      const serverHash = await sha256(content)

      if (localHash === serverHash) {
        // Same content, just record the new etag
        this.baseline[sp] = { etag, hash: serverHash }
        return
      }

      const localEdited = base ? localHash !== base.hash : true
      if (localEdited) {
        // Both sides changed (or first sync with diverging copies):
        // keep the local version next to the file, take the server's
        await this.saveConflictCopy(vp, localContent)
        stats.conflicts++
      }

      await this.writeVaultFile(vp, content)
      this.baseline[sp] = { etag, hash: serverHash }
      stats.pulled++
      return
    }

    if (base) {
      // We synced this before and the local copy is gone — the local
      // delete wins nothing; the server is source of truth, re-download.
      // (Deleting entities happens in the app, not by removing files.)
    }
    const { content, etag } = await this.client.getFile(sp)
    await this.writeVaultFile(vp, content)
    this.baseline[sp] = { etag, hash: await sha256(content) }
    stats.pulled++
  }

  /** The server no longer has this file — remove the local copy. */
  private async applyServerDeletion(sp: string, stats: SyncStats): Promise<void> {
    const vp = this.vaultPath(sp)
    const existing = this.app.vault.getAbstractFileByPath(vp)

    if (existing instanceof TFile) {
      const localContent = await this.app.vault.read(existing)
      const base = this.baseline[sp]
      if (base && (await sha256(localContent)) !== base.hash) {
        // Local edits would be lost — keep them as a conflict copy
        await this.saveConflictCopy(vp, localContent)
        stats.conflicts++
      }
      this.applyingRemote.add(vp)
      try {
        // trashFile respects the user's "deleted files" preference
        await this.app.fileManager.trashFile(existing)
      } finally {
        this.scheduleRemoteClear(vp)
      }
      stats.deleted++
    }
    delete this.baseline[sp]
  }

  /** Push one file; resolves 412 conflicts by letting the server win. */
  async pushOne(sp: string, content: string, stats: SyncStats): Promise<void> {
    const base = this.baseline[sp]
    const result = await this.client.putFile(sp, content, base?.etag)

    if (result.ok) {
      this.baseline[sp] = { etag: result.etag, hash: await sha256(content) }
      stats.pushed++
      return
    }

    if (result.status === 412) {
      // Server has a version we haven't seen. Keep our edit as a
      // conflict copy, then adopt the server version.
      const vp = this.vaultPath(sp)
      try {
        const { content: serverContent, etag } = await this.client.getFile(sp)
        await this.saveConflictCopy(vp, content)
        await this.writeVaultFile(vp, serverContent)
        this.baseline[sp] = { etag, hash: await sha256(serverContent) }
        stats.conflicts++
        new Notice(`Wedding Computer: "${sp}" changed on the server. Your edit was saved as a .conflict.md copy.`)
      } catch (err) {
        stats.errors.push(`${sp}: conflict resolution failed: ${message(err)}`)
      }
      return
    }

    // 422 (not ingestible — e.g. a handwritten file with no id) or other
    stats.errors.push(`${sp}: ${result.error}`)
  }

  /** Debounced single-file push used by the vault modify handler. */
  async pushPath(vaultPath: string): Promise<SyncStats | null> {
    const sp = this.serverPath(vaultPath)
    if (!sp || !this.isPushable(sp)) return null

    const file = this.app.vault.getAbstractFileByPath(vaultPath)
    if (!(file instanceof TFile)) return null

    const stats: SyncStats = { pulled: 0, pushed: 0, deleted: 0, conflicts: 0, errors: [] }
    const content = await this.app.vault.read(file)
    const hash = await sha256(content)
    const base = this.baseline[sp]
    if (base && base.hash === hash) return stats

    await this.pushOne(sp, content, stats)
    await this.persistBaseline()
    return stats
  }

  /**
   * Markdown files inside the synced folder only — the plugin never
   * needs to enumerate the rest of the vault.
   */
  private collectSyncedFiles(): TFile[] {
    const rootPath = this.baseFolder ? normalizePath(this.baseFolder) : '/'
    const root = this.app.vault.getAbstractFileByPath(rootPath)
    if (!(root instanceof TFolder)) return []

    const files: TFile[] = []
    const walk = (folder: TFolder): void => {
      for (const child of folder.children) {
        if (child instanceof TFolder) walk(child)
        else if (child instanceof TFile && child.extension === 'md') files.push(child)
      }
    }
    walk(root)
    return files
  }

  // ── Vault helpers ──

  private async writeVaultFile(vaultPath: string, content: string): Promise<void> {
    await this.ensureParentFolders(vaultPath)
    const existing = this.app.vault.getAbstractFileByPath(vaultPath)

    this.applyingRemote.add(vaultPath)
    try {
      if (existing instanceof TFile) {
        await this.app.vault.modify(existing, content)
      } else {
        await this.app.vault.create(vaultPath, content)
      }
    } finally {
      this.scheduleRemoteClear(vaultPath)
    }
  }

  private async saveConflictCopy(vaultPath: string, content: string): Promise<void> {
    const conflictPath = vaultPath.replace(/\.md$/, '.conflict.md')
    await this.writeVaultFile(conflictPath, content)
  }

  private async ensureParentFolders(vaultPath: string): Promise<void> {
    const parts = vaultPath.split('/')
    parts.pop() // the filename
    let current = ''
    for (const part of parts) {
      current = current ? `${current}/${part}` : part
      const existing = this.app.vault.getAbstractFileByPath(current)
      if (existing instanceof TFolder) continue
      if (!existing) {
        try {
          await this.app.vault.createFolder(current)
        } catch {
          /* races with another create are fine */
        }
      }
    }
  }

  /** Keep the self-write guard up long enough for vault events to fire. */
  private scheduleRemoteClear(vaultPath: string): void {
    window.setTimeout(() => this.applyingRemote.delete(vaultPath), 1500)
  }
}

function message(err: unknown): string {
  return err instanceof Error ? err.message : String(err)
}

async function sha256(content: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(content))
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('')
}
